### ISSUE TITLE
Implement /latestaudio function

### ISSUE THREAD

**Issue by lydgate** [Gryphire/wisperbot#6]
For the bloom bot, which was a social experiment, I built a `/latest` command which concatenated the last 5 audio files that had been submitted to the bot (sent by anyone) and sends them in a single voicenote back to the user.

For wisper, I'm not sure this is appropriate behaviour since it can reveal other people's voicenotes. Is that the intention? If so we should talk about how that works (possibly just as simple as uncommenting the old function if that's really what we want).

But if what we want is to send the last message back from a single user chat, it would require a new function.

**Comment by Gryphire** [comment]
Indeed, concatenation of last 5 audio messages is not necessary for Wisperbot. Have now commented this function (i.e., _concat_voicenotes_) out.

I am keeping in the _latestaudio_ function though, since people might want to be reminded what the last audio message was that they've received (e.g. in the scenario in which people also communicate in the chat through text, audio messages might disappear from view easily). I've added a minor fix to the function to match the refactoring you did, so that works now again.
As far as audio handling goes, I think this covers all of our Wisper needs so far. 👍🏻
