### ISSUE TITLE
Status unexpectedly reverts to "received_week1_ps" 

### ISSUE THREAD

**Issue by Gryphire** [Gryphire/wisperbot#60]
In our latest test, my dyad partner and I reached the point where we record our final responses of the week. In my case, the audio was correctly registered as a 'final response' (and the status was correctly changed from 'awaiting_week1_feedback' to 'received_week1_feedback'), but in my partner's case the code went back in time, and instead of registering their audio as the final feedback, it registered it as the curious listening response (setting their status from awaiting_week1_feedback to received_week1_ps).

Just as a point of chronology, she was the first out of us two to send in her final feedback, so the reversion happened before I had sent in my final feedback as well. So by the time I had done that, we were both stuck and neither of us received the other's final feedback audio. (: 

Attaching the central log, see the row that starts with "2024-07-13 15:51:33,591" (row 938) for the row where the status reverts unexpectedly.

[central_log.log](https://github.com/user-attachments/files/16261441/central_log.log)

**Comment by lydgate** [comment]
Phew! OK, I believe this should be fixed in this branch, can you test? It should now wait for 1-2 messages from each person for the final response, and then exchange them before moving to week 2. It's quite complicated why this wasn't working but I think this should hopefully fix it. It looks like my editor might have switched a few of your quotes as well, hope that is not too disruptive but maybe look at the change.

**Comment by Gryphire** [comment]
Oh great! Sorry to hear it was a fuss! I definitely want to try out again, but I just received word of another issue (one that I at least hadn't encountered before). I will post in another issue, and then maybe you could check that out, see what's up before I do a new test?

**Comment by lydgate** [comment]
Yep sounds good! Thanks :)

**Comment by Gryphire** [comment]
Is fixed!
